NAME            = 'xml.easy'
VERSION         = '1.0'
MODULE_DEPS     = 'xml.lite io mem mt logging str coda_oss'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())