NAME            = 'mt'
MAINTAINER      = 'jmrandol@users.sourceforge.net'
VERSION         = '1.1'
USE             = 'OPENCV_HIGHGUI OPENCV_TS'
MODULE_DEPS     = 'sys except mem'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
