NAME            = 'simd'
VERSION         = '1.0'
MODULE_DEPS     = 'vectorclass coda_oss config gsl sys'
TEST_DEPS       = 'std'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
    
