NAME            = 'xml.dom'
VERSION         = '1.0'
MODULE_DEPS     = 'xml.lite io mem mt logging str coda_oss'
USELIB_CHECK    = 'XML'
TEST_DEPS       = 'cli'

options = distclean = lambda p: None

from waflib import Options
from build import writeConfig

def configure(conf):
    # callback function to check for #defines used by the xml.lite module
    def xml_lite_callback(conf):
        if Options.options.xml_layer == 'xerces':
            conf.define('USE_XERCES', '', quote=False)

    writeConfig(conf, xml_lite_callback, NAME)

def build(bld):
    bld.module(**globals())
