NAME            = 'enums'
VERSION         = '1.0'
MODULE_DEPS     = 'str except coda_oss'
UNITTEST_DEPS   = 'std'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())

