NAME            = 'types'
VERSION         = '1.0'
MODULE_DEPS     = 'gsl coda_oss'
UNITTEST_DEPS   = 'sys'

options = configure = distclean = lambda p: None

def build(bld):
    bld.module(**globals())
    
